#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/fc569885-5ea9-4e82-9a71-c2b765ee0960 # 
title: sample https
version : 1.0
/getDate:
  get:
    responses: 
      200:
        body:
          application/json: 
            example : |
              {
                "statas":"success"
               }  